// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NavBeacon.Server.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NavBeacon.Server.Persistence.Migrations
{
    [DbContext(typeof(NavBeaconDbContext))]
    [Migration("20260911161836_InitialCommanderSchema")]
    partial class InitialCommanderSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.CommanderAccount", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("commander_name");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_access_token");

                    b.Property<string>("ProtectedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_refresh_token");

                    b.Property<long>("RecordRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("record_revision");

                    b.HasKey("CustomerId");

                    b.ToTable("commander_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_commander_accounts_name", "char_length(commander_name) > 0");

                            t.HasCheckConstraint("ck_commander_accounts_revision", "record_revision >= 0");
                        });
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.CommanderSession", b =>
                {
                    b.Property<byte[]>("SessionHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("session_hash");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("LastRenewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_renewed_at");

                    b.Property<DateTimeOffset>("RenewableExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewable_expires_at");

                    b.HasKey("SessionHash");

                    b.HasIndex("AbsoluteExpiresAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RenewableExpiresAt");

                    b.ToTable("commander_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_commander_sessions_lifetime", "created_at <= last_renewed_at AND last_renewed_at < absolute_expires_at AND renewable_expires_at > last_renewed_at AND renewable_expires_at <= absolute_expires_at AND renewable_expires_at <= last_renewed_at + interval '30 days' AND absolute_expires_at = created_at + interval '180 days'");
                        });
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.JournalCursor", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("CoverageStartDate")
                        .HasColumnType("date")
                        .HasColumnName("coverage_start_date");

                    b.Property<bool?>("LastStoredShipsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("last_stored_ships_complete");

                    b.Property<DateOnly?>("LastStoredShipsDate")
                        .HasColumnType("date")
                        .HasColumnName("last_stored_ships_date");

                    b.Property<int?>("LastStoredShipsLine")
                        .HasColumnType("integer")
                        .HasColumnName("last_stored_ships_line");

                    b.Property<DateTimeOffset?>("NextPermittedRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_permitted_refresh_at");

                    b.Property<DateOnly>("NextUnreadDate")
                        .HasColumnType("date")
                        .HasColumnName("next_unread_date");

                    b.Property<int>("NextUnreadLine")
                        .HasColumnType("integer")
                        .HasColumnName("next_unread_line");

                    b.HasKey("CustomerId");

                    b.ToTable("journal_cursors", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_cursors_lines", "next_unread_line >= 0 AND (last_stored_ships_line IS NULL OR last_stored_ships_line >= 0)");

                            t.HasCheckConstraint("ck_journal_cursors_stored_ships", "(last_stored_ships_date IS NULL AND last_stored_ships_line IS NULL AND last_stored_ships_complete IS NULL) OR (last_stored_ships_date IS NOT NULL AND last_stored_ships_line IS NOT NULL AND last_stored_ships_complete IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.OAuthAttempt", b =>
                {
                    b.Property<byte[]>("StateHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("state_hash");

                    b.Property<byte[]>("BrowserCorrelationHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("browser_correlation_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("StateHash");

                    b.HasIndex("BrowserCorrelationHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.ToTable("oauth_attempts", (string)null);
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.OwnedShip", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("ShipId")
                        .HasColumnType("bigint")
                        .HasColumnName("ship_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateOnly>("SourceDate")
                        .HasColumnType("date")
                        .HasColumnName("source_date");

                    b.Property<int>("SourceLine")
                        .HasColumnType("integer")
                        .HasColumnName("source_line");

                    b.HasKey("CustomerId", "ShipId");

                    b.HasIndex("CustomerId", "SourceDate", "SourceLine")
                        .IsUnique();

                    b.ToTable("owned_ships", null, t =>
                        {
                            t.HasCheckConstraint("ck_owned_ships_source_line", "source_line >= 0");
                        });
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.SynchronisedRecord", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<DateTimeOffset?>("BrowserModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("browser_modified_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProtectionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("protection_deadline");

                    b.Property<string>("RecordKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("record_kind");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("ServerContentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_content_at");

                    b.HasKey("CustomerId", "RecordId");

                    b.HasIndex("CustomerId", "Revision")
                        .IsUnique();

                    b.ToTable("synchronised_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_synchronised_records_exact_shape", "(payload IS NULL AND record_kind IS NULL AND name IS NULL AND created_at IS NULL AND browser_modified_at IS NULL AND server_content_at IS NULL AND protection_deadline IS NULL) OR (payload IS NOT NULL AND record_kind IS NOT NULL AND created_at IS NOT NULL AND browser_modified_at IS NOT NULL AND server_content_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_synchronised_records_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.CommanderSession", b =>
                {
                    b.HasOne("NavBeacon.Server.Persistence.CommanderAccount", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.JournalCursor", b =>
                {
                    b.HasOne("NavBeacon.Server.Persistence.CommanderAccount", "Account")
                        .WithOne("JournalCursor")
                        .HasForeignKey("NavBeacon.Server.Persistence.JournalCursor", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.OwnedShip", b =>
                {
                    b.HasOne("NavBeacon.Server.Persistence.CommanderAccount", "Account")
                        .WithMany("OwnedShips")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.SynchronisedRecord", b =>
                {
                    b.HasOne("NavBeacon.Server.Persistence.CommanderAccount", "Account")
                        .WithMany("SynchronisedRecords")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NavBeacon.Server.Persistence.CommanderAccount", b =>
                {
                    b.Navigation("JournalCursor");

                    b.Navigation("OwnedShips");

                    b.Navigation("Sessions");

                    b.Navigation("SynchronisedRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
